BP-872 - Add Scheduler project to the Blueprint Template
enigmatry/entry-blueprint pull request #19
Opened 2024-03-25 12:11 UTC by laslorajda

BP-872

2024-03-25 15:35 UTC, zsrdjan requested changes

2024-03-25 15:35 UTC, zsrdjan commented on Enigmatry.Entry.Blueprint.Scheduler/Program.cs
> +    using var factory = new SerilogLoggerFactory();
Is this scheduler configured completely. I.e. can you resolve IRepository, send MediatR request?

2024-03-25 15:35 UTC, zsrdjan commented on Enigmatry.Entry.Blueprint.Scheduler/Jobs/EntryBlueprintExampleJob.cs
> +        _logger.LogInformation("Scheduled job executed at {Now}", DateTimeOffset.Now);
Can we create a job that will create a user in the local database?

2024-03-25 15:35 UTC, zsrdjan commented on Enigmatry.Entry.Blueprint.Scheduler/Program.cs
> +    using var factory = new SerilogLoggerFactory();
Scheduler.Tests project is missing.

2024-03-26 13:27 UTC, laslorajda commented on Enigmatry.Entry.Blueprint.Scheduler.Tests/SchedulerFixtureBase.cs
> +        if (dbContext.Set<User>().SingleOrDefault(x => x.Id == testUser.Id) != null)
I don't love this, but seeding/migration will create this user initially and then respawn will delete it. Couldn't think of a better solution.

2024-04-01 16:00 UTC, zsrdjan approved these changes

2024-04-01 16:21 UTC, merged