BP-719: Theming: add documentation for setup from scratch
enigmatry/entry-blueprint pull request #3
Opened 2024-01-05 13:32 UTC by Cvetanovic

https://enigmatry.atlassian.net/browse/BP-719

2024-01-11 13:02 UTC, typhoon41 commented on enigmatry-entry-blueprint-app/theming-setup.md
> +We're overriding Angular Material, so it is important to add CSS classes for mixin that emit styles for native header elements. In another case, if don't provide those classes for custom components,
Why would anyone care we're overriding AM? We just need to say, please use this here and there for the right effect.

2024-01-12 14:38 UTC, Cvetanovic commented on enigmatry-entry-blueprint-app/theming-setup.md
> +|                  | family                          | ''                                  |
The letter spacing is only missing, and when we merge that PR, also here, we need to change the font-size value 0 to null

2024-01-15 15:02 UTC, typhoon41 requested changes

2024-01-15 15:02 UTC, typhoon41 commented on enigmatry-entry-blueprint-app/theming-setup.md
> +Inside the `$custom-theme` map, you can define custom styles to suit specific preferences and needs.
Please make a link here for "default theme" so user can jump easily.

2024-01-22 13:44 UTC, jovana-marceta approved these changes

2024-01-22 20:53 UTC, typhoon41 commented on enigmatry-entry-blueprint-app/theming-setup.md
> +@use 'entry-components/styles/generator';
For this to work, it is expected to add shortcut in angular.json towards node_modules/@enigmatry. This has to be mentioned.

2024-01-22 20:57 UTC, typhoon41 commented on enigmatry-entry-blueprint-app/theming-setup.md
> +
We already have this mentioned in more detailed guide. Just fill up some holes there (if any).

2024-01-22 20:59 UTC, typhoon41 commented on enigmatry-entry-blueprint-app/README.md
File still exists :)

2024-01-23 12:36 UTC, jovana-marceta commented on enigmatry-entry-blueprint-app/README.md
@typhoon41 @Cvetanovic  I moved theme setup docs to entry-components, and I create separated PR https://github.com/enigmatry/entry-angular-building-blocks/pull/181

2024-01-23 12:39 UTC, jovana-marceta commented on enigmatry-entry-blueprint-app/theming-setup.md
> +
I create one section for all important links under "Theming Configuration Sections" in separated PR

2024-01-30 08:34 UTC, typhoon41 commented on enigmatry-entry-blueprint-app/theming-setup.md
> +- [Overview](#overview)
Since we moved setup doc file to angular building blocks this can be removed? Once that takes place, I'll approve this PR.

2024-01-30 13:16 UTC, typhoon41 approved these changes

2024-01-30 13:18 UTC, merged